name: balance
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  drift:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  go_router: ^12.1.1 
  hooks_riverpod: ^2.4.9
  injectable:
  path:
  path_provider:
  sqlite3_flutter_libs:
  uuid:

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev:
  flutter_test:
    sdk: flutter
  injectable_generator:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
